# coding: utf-8

"""
    Database API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.databases_name_body import DatabasesNameBody  # noqa: E501
from swagger_client.rest import ApiException


class TestDatabasesNameBody(unittest.TestCase):
    """DatabasesNameBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatabasesNameBody(self):
        """Test DatabasesNameBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.databases_name_body.DatabasesNameBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
