name: http_server
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  core:
    path: ../core
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
